### ISSUE TITLE
Unrecognized header format % error

### ISSUE THREAD

**Issue by muhiamwangi** [k00lith/ALL#2]
Hi @k00lith 
Thank you for your such a helpful NetBox on CentOS7 installation walkthrough guide.
I followed through for most part but encounter this error when i restart the server(step26, 27) :  " **Unrecognized header format %** " .
I have tried this by doesn't help.--> RequestHeader set **"X-Forwarded-Proto" expr="%{REQUEST_SCHEME}"**

I would appreciate any workaround leads.

Attached are the screenshots of the related files:

![Unrecognized header format%](https://user-images.githubusercontent.com/38052222/190226462-984fb0e1-7182-4e25-b77e-b2b1472d6363.PNG)
![%](https://user-images.githubusercontent.com/38052222/190226475-49084093-4dad-46ed-b608-fa938dc2bc61.PNG)

**Comment by k00lith** [comment]
Hi, @muhiamwangi , i check my work apache config and i think you should try ONLY this lines in netbox.conf, try it as a test:


```
Listen 8045
<VirtualHost 192.168.194.138:8045>
    ProxyPreserveHost On
    ServerName 192.168.194.138
    SSLEngine on
    SSLCertificateFile /etc/ssl/certs/netbox.crt
    SSLCertificateKeyFile /etc/ssl/private/netbox.key
    Alias /static /opt/netbox/netbox/static
    <Directory /opt/netbox/netbox/static>
        Options Indexes FollowSymLinks MultiViews
        AllowOverride None
        Require all granted
    </Directory>
    <Location /static>
        ProxyPass !
    </Location>
    ProxyPass / http://127.0.0.1:8001/
    ProxyPassReverse / http://127.0.0.1:8001/
</VirtualHost>
```

dont forget
```
systemctl restart httpd
```

**Comment by muhiamwangi** [comment]
Cheers, Its working as expected now :)
That helped.

Thank you @k00lith
